environments:
  Web.DEVCI:
    pipelines:
      - beta-parliament-functional-tests
pipelines:
  beta-parliament-functional-tests
    group: Testing
    label_template: "${COUNT}"
    materials: parliament.uk-awt
      git: https://github.com/jehudson/parliament.uk-awt.git
      branch: WEBDEV-398
      auto_update: true
  stages:
    - build:
        clean_workspace: true
        jobs:
          npm:
            - exec:
                run_if: passed
                command: npm
                arguments:
                  - i
