environments:
  Web.DEVCI:
    pipelines:
      - beta-parliament-awt
pipelines:
  beta-parliament-awt:
    group: testing
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/jehudson/parliament.uk-awt.git
        branch: WEBDEV-398
    stages:
      - build:
          clean_workspace: true
          jobs:
            npm:
              tasks:
                - exec:
                  command: npm
                  arguments:
                    - "i"
